definitions:
  api.ResponseError:
    type: object
  api.ResponseFile:
    type: object
info:
  contact: {}
paths:
  /files:
    get:
      operationId: getFiles
      produces:
      - application/json
      responses:
        "200":
          description: Files available
          schema:
            items:
              $ref: '#/definitions/api.ResponseFile'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ResponseError'
      summary: Get all files on the server
      tags:
      - files
    post:
      operationId: getFile
      parameters:
      - description: ID of file
        in: path
        name: fileID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: File info
          schema:
            $ref: '#/definitions/api.ResponseFile'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/api.ResponseError'
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/api.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ResponseError'
      summary: Get file info
      tags:
      - files
swagger: "2.0"
